apiVersion: apps/v1
kind: Deployment
metadata:
  name: pugster-backend
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pugster-backend
  template:
    metadata:
      labels:
        app: pugster-backend
    spec:
      containers:
        - name: pugster-backend
          image: ghcr.io/brendajanos/pugster:sha-f68ff6d
          ports:
            - name: http
              containerPort: 8080
