version: "3.7"

services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pugster
    ports:
      - "27017:27017"

  app:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: mongodb://pugster:pugster@mongo:27017/pugster



